export enum Tables {
  Plan = 'Plan',
  Subscription = 'Subscription',
  TvShow = 'TvShow',
  Episode = 'Episode',
  Content = 'Content',
  Movie = 'Movie',
  Thumbnail = 'Thumbnail',
  Video = 'Video',
  User = 'User',
  Invoice = 'BillingInvoice',
  InvoiceLineItem = 'BillingInvoiceLineItem',
  Charge = 'BillingCharge',
  Credit = 'BillingCredit',
  AddOn = 'BillingAddOn',
  SubscriptionAddOn = 'BillingSubscriptionAddOn',
  UsageRecord = 'BillingUsageRecord',
  Discount = 'BillingDiscount',
  SubscriptionDiscount = 'BillingSubscriptionDiscount',
  Payment = 'BillingPayment',
  TaxRate = 'BillingTaxRate',
  DunningAttempt = 'BillingDunningAttempt',
  TaxCalculationSummary = 'BillingTaxCalculationSummary',
  TaxCalculationError = 'BillingTaxCalculationError',
}
